### ISSUE TITLE
Add Support for Broadlink RM4 pro (0x653C)

### ISSUE THREAD

**Issue by lukeclx** [mjg59/python-broadlink#480]
Seems like it's not supported for Broadlink RM4 pro (0x653C)

_Originally posted by @lukeclx in https://github.com/mjg59/python-broadlink/issues/472#issuecomment-731774318_

Home Assistant 0.118.3

**Comment by Boussen** [comment]
same for me

**Comment by paradoxm** [comment]
I set `**0x653C: (rm4, "RM4 pro", "Broadlink")**`, into the file **brodlink/__init__.py** and now it works as well

**Comment by glorifiedg** [comment]
Where is the file located so I can edit it?

**Comment by KTibow** [comment]
@glorifiedg make a new issue for that.
@felipediel do you have a open PR already, or can you make one?

**Comment by k7franklin** [comment]
I have two rm4c thats not working in ha. Other, with other hash is working fine.

We will have support for they?

**Comment by KTibow** [comment]
@k7franklin RM4C is different than RM4 pro. If your hash code is the same one as this PR, then it should fix it.

**Comment by opep** [comment]
> 
> 
> I have two rm4c thats not working in ha. Other, with other hash is working fine.
> 
> We will have support for they?

The answer is most likely yes.
https://github.com/lbschenkel/broadlink-bridge/pull/7

**Comment by XxCabbyoO** [comment]
Same error with RM4C mini

Unsupported device: 0x6539

**Comment by opep** [comment]
> 
> 
> Where is the file located so I can edit it?

I also solved by myself, having found the solution (for now):
![image](https://user-images.githubusercontent.com/40412787/102418057-c5920180-3fdb-11eb-9982-7e684eb1ad03.png)

**Comment by fjcargom** [comment]
> I set **0x653C: (rm4, "RM4 pro", "Broadlink")**, into the file **brodlink/**init**.py** and now it works as well

Sigue sin funcionar y esta añadida la linea indicada.

It still does not work and the indicated line is added

**Comment by felipediel** [comment]
Did you restart the server? If positive, check if the type is correct.

**Comment by fjcargom** [comment]
El servidor está reiniciado y sigue fallado, además esta desactivado la opcion de "Bloquear dispositivo" dentro de la aplicación Broadlink. Se trata de un RM4 Procon Firmware V52079
------------
The server is rebooted and still crashed, also the "Block device" option is disabled within the Broadlink application. It is a RM4 Procon Firmware V52079

**Comment by felipediel** [comment]
Your device type is probably different. I need to see the error message. There is a hexadecimal value, it's your PID, please send me so we can add it.

**Comment by fjcargom** [comment]
ERROR:
Logger: homeassistant.components.broadlink.config_flow
Source: components/broadlink/config_flow.py:48
Integration: Broadlink (documentation, issues)
First occurred: 12:00:05 (7 occurrences)
Last logged: 16:30:58

Unsupported device: 0x653c. If it worked before, please open an issue at https://github.com/home-assistant/core/issues
-----------------
My home assistant is installed on a raspberry pi 3 model B

**Comment by felipediel** [comment]
1. Open Home Assistant and install "SSH & Web Terminal" add-on
2. Disable Protection mode
3. Connect to the device via SSH and install the patch:
```
ssh USER@IPADDRESS
docker exec -it homeassistant /bin/bash
pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
```
4. Restart the server.

**Comment by fjcargom** [comment]
---
Thank you very much for your help, I have finally made it, great support.
---

**Comment by felipediel** [comment]
Thanks for reporting back!

**Comment by dablanco83** [comment]
Thanks! This also worked for me here with the RM4 Pro that I tried today. Much appreciated!

**Comment by Rogi66** [comment]
felipediel you are a hero! It also worked for me! Will this change automatically be added to the next version of HA?

**Comment by KTibow** [comment]
Once #472 gets merged, another version of this lib gets released, HA gets updated to use it, and a new HA release is made.

**Comment by Paulie-Moo** [comment]
> pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps

I use this every time there is a HA update. keeps working every time with my UK/USA RM4 Pro.
Cant wait for it to be rolled into an RC update

Thank you !!!

**Comment by healeydave** [comment]
Any tips for this running Home Assistant on a Raspberry Pi?

It doesn't appear these fixes have been rolled into the latest versions of Home Assistant.
I have a RPi 4 running 2021 Home Assistant version 5.10

I have terminal installed but I don't think the commands above are relevant with this type of installation.

**Comment by fjcargom** [comment]
> 1. Open Home Assistant and install "SSH & Web Terminal" add-on
> 2. Disable Protection mode
> 3. Connect to the device via SSH and install the patch:
> 
> ```
> ssh USER@IPADDRESS
> docker exec -it homeassistant /bin/bash
> pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
> ```
> 
> 1. Restart the server.

The patch is not yet applied in the new versions of Home Assistant so you have to continue applying the patch by hand.
In my case I also have a Raspberry Pi 3 and it works correctly.

**Comment by dablanco83** [comment]
For part 3.  I just click on ”Open web-UI” in the SSH and web terminal under the supervisor menu and paste the text there.

**Comment by healeydave** [comment]
docker commands not found.

**Comment by fjcargom** [comment]
You must disable protected mode for the command to work.

**Comment by fjcargom** [comment]
[If]([url]([url](url))) you have the addon "SSH & Web Terminal" you must deactivate the "Protection mode", restart the addon so that the changes take effect and once you start using "open Web UI" execute the commands indicated a little above.

![Protection mode](https://user-images.githubusercontent.com/75100592/105342911-3e8b0700-5be1-11eb-8fd8-3104a0c72f0d.JPG)

**Comment by healeydave** [comment]
Thank you. The problem was I had installed the Official Terminal & SSH package from Home Assistant which doesn't have a "Disable Protection" mode option.

**Comment by maeneak** [comment]
After upgrading to HA core-2021.1.4 this workaround doesnt work for me anymore. After a restart the broadlink module reverts back to release

**Comment by dablanco83** [comment]
Hi. I can confirm that this workaround works on 2012.1.5. Never tried 2.1.4. And everyone should update to .2012.1.5 due to the security issues found in earlier versions.

**Comment by steelincable** [comment]
I also confirm the fix from @fjcargom works on 2021.1.5 on my new RM4 Pro ordered from AliExpress and installed today.  I had the same issue as @healeydave and wasted 30 minutes looking for a 'disable protection' switch all over HA (newb here).  It pays to read the whole thread, thank you both!

**Comment by Blitzpulli** [comment]
Hi ! I have the same issue with my new rm4c.
I struggle with SSH & Web Terminal.
When I try to open the web UI, I get a '502: Bad Gateway' error.
I find no errors in the logs. What is wrong ?

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] permissions: applying... 
[fix-attrs.d] permissions: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: SSH & Web Terminal
 SSH & Web Terminal access to your Home Assistant instance
-----------------------------------------------------------
 Add-on version: 7.8.0
 You are running the latest version of this add-on.
 System: null  (amd64 / qemux86-64)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[15:55:24] INFO: Docker support has been enabled.
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] docker.sh: executing... 
[cont-init.d] docker.sh: exited 0.
[cont-init.d] mosquitto.sh: executing... 
[cont-init.d] mosquitto.sh: exited 0.
[cont-init.d] mysql.sh: executing... 
[cont-init.d] mysql.sh: exited 0.
[cont-init.d] ssh.sh: executing... 
[15:55:26] INFO: Password is NOT in the Have I Been Pwned database! Nice!`

**Comment by Blitzpulli** [comment]
So I finally made, it. But through the homeassistant container console in portainer, as root. See below the result. But the device is still unsupported.

`bash-5.0# pip3 install git+https://github.com/felipediel/python-broadlink.git@patch-23 --force-reinstall --no-deps
Collecting git+https://github.com/felipediel/python-broadlink.git@patch-23
  Cloning https://github.com/felipediel/python-broadlink.git (to revision patch-23) to /tmp/pip-req-build-48zkgisz
Building wheels for collected packages: broadlink
  Building wheel for broadlink (setup.py) ... done
  Created wheel for broadlink: filename=broadlink-0.16.0-py3-none-any.whl size=18265 sha256=efe8c801512bd995c37456084ef64dfe2e9cf7540db69e44f1f365ac20223452
  Stored in directory: /tmp/pip-ephem-wheel-cache-_7s81qtz/wheels/7a/83/05/eb28ed808c159d54d49eae6de18f6b4705e094bfe3009f8ead
Successfully built broadlink
Installing collected packages: broadlink
  Attempting uninstall: broadlink
    Found existing installation: broadlink 0.16.0
    Uninstalling broadlink-0.16.0:
      Successfully uninstalled broadlink-0.16.0
Successfully installed broadlink-0.16.0
WARNING: You are using pip version 20.2.4; however, version 21.0 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.`

**Comment by Blitzpulli** [comment]
Ok, last message for me on this problem. I swear.
I solved the issue with this method: https://community.home-assistant.io/t/broadlink-rm4-pro-device-not-supported/250996/9?u=quart-temps

In fact, my device was RM4C mini 0x6539.

**Comment by morettty** [comment]
> Ok, last message for me on this problem. I swear.
> I solved the issue with this method: https://community.home-assistant.io/t/broadlink-rm4-pro-device-not-supported/250996/9?u=quart-temps
> 
> In fact, my device was RM4C mini 0x6539.

I have the same problem with synology and I am not able to get it to work. If you can explain the steps to fix it, I will be very grateful

**Comment by shali3** [comment]
It is very frustrating to keep fixing this issue manually with every update of home assistant.
I see that the 0x6539 is already included in master but was not part of the recent (January) release. 

Can you please cut another release from master?

Thanks 🙏🏽

**Comment by Blitzpulli** [comment]
> 
> 
> > Ok, last message for me on this problem. I swear.
> > I solved the issue with this method: https://community.home-assistant.io/t/broadlink-rm4-pro-device-not-supported/250996/9?u=quart-temps
> > In fact, my device was RM4C mini 0x6539.
> 
> I have the same problem with synology and I am not able to get it to work. If you can explain the steps to fix it, I will be very grateful

I did like described in the link. Where are you stuck ?

**Comment by KTibow** [comment]
> Can you please cut another release from master?
Thanks 🙏🏽

The person who made the PR to fix this doesn't have permission to publish to PyPi.

**Comment by mjg59** [comment]
I've added @felipediel to the PyPi project

**Comment by felipediel** [comment]
Thank you @mjg59! I am working on version 0.17.0 and will release it as soon as it is ready.

**Comment by KTibow** [comment]
@felipediel if you want, you can generate an API key so GitHub actions can auto-publish to PyPi for you. I can send in the PR.

**Comment by felipediel** [comment]
Sounds good, what triggers the auto-publishing?

**Comment by KTibow** [comment]
Whenever a GitHub release is published.

**Comment by hellcry37** [comment]
Why is taking so long to add RM4 Pro to Broadlink integration, I might be ignorant and don't know what it involves but from nobember to march next year is a bit much no?

I mean I sow devices added in less then 2 weeks, anyone care to enlighten us commons?

Thanks in advance and I apologize if I sounded arrogant, is the frustration reaching critical levels.

**Comment by kylemd** [comment]
@hellcry37 open source projects are a labour of love, and as a result there's no ETAs.

Felipe has been very active though - from what I understand from following the project closely he's trying to tidy up protocol related matters so it all works 100% reliably.

**Comment by hellcry37** [comment]
ty

**Comment by felipediel** [comment]
Hi @KTibow. I think automating releases is a good idea. Could you please send that PR?

**Comment by KTibow** [comment]
I sent it; however only the original owner can add secrets from my knowledge.

**Comment by felipediel** [comment]
Fixed with https://github.com/mjg59/python-broadlink/pull/472.
